# Generated by Django 4.1 on 2022-09-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_product_brand_remove_product_creatat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessoir',
            old_name='name',
            new_name='carburant',
        ),
        migrations.RenameField(
            model_name='accessoir',
            old_name='original_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='accessoir',
            name='creatat',
        ),
        migrations.RemoveField(
            model_name='accessoir',
            name='description',
        ),
        migrations.RemoveField(
            model_name='accessoir',
            name='modele',
        ),
        migrations.RemoveField(
            model_name='accessoir',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='accessoir',
            name='small_description',
        ),
        migrations.AddField(
            model_name='accessoir',
            name='km',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='accessoir',
            name='version',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
