# Generated by Django 4.1 on 2022-09-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_name_accessoir_carburant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoir',
            name='boitevitesse',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
