# Generated by Django 4.1 on 2022-09-14 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_accessoir_boitevitesse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='original_price',
        ),
    ]
