# Generated by Django 4.1 on 2022-09-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_product_original_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='modele',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='position',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
