# Generated by Django 4.1 on 2022-09-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_product_modele_product_brand_product_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
