# Generated by Django 4.1 on 2022-09-15 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
    ]
